name: Création du zip de l'extension Wordpress
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the date
        id: date
        run: |
          export TZ=America/Toronto
          echo "date=$(date +'%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Read INFOS.json
        id: infos
        run: |
          echo "dev=$(jq -r .dev INFOS.json)" >> $GITHUB_ENV
          echo "version=$(jq -r .version INFOS.json)" >> $GITHUB_ENV
        shell: bash

      - name: Change version in files
        run: |
          VERSION="${{ env.version }}${{ env.dev == 'true' && '-dev-' || '' }}${{ env.dev == 'true' && env.date || '' }}"
          DEV=${{ env.dev }}
          # Mise à jour dans acary-cloud-helper.php
          sed -i "s/Version: .*/Version: $VERSION/g" acary-cloud-helper.php
          sed -i "s/define( 'ACARYCLOUDHELPER_VERSION', '.*' );/define( 'ACARYCLOUDHELPER_VERSION', '$VERSION' );/g" acary-cloud-helper.php
          sed -i "s/define( 'ACARYCLOUDHELPER_VERSIONDEV', .*/define( 'ACARYCLOUDHELPER_VERSIONDEV', $DEV );/g" acary-cloud-helper.php
          # Mise à jour dans readme.txt
          sed -i "s/Stable tag: .*/Stable tag: $VERSION/g" readme.txt

      - name: Commit and push version changes
        run: |
          VERSION="${{ env.version }}${{ env.dev == 'true' && '-dev-' || '' }}${{ env.dev == 'true' && env.date || '' }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add acary-cloud-helper.php readme.txt
          git commit -m "Update version to $VERSION"
          git push

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: "${{ env.version }}${{ env.dev == 'true' && '-dev-' || '' }}${{ env.dev == 'true' && env.date || '' }}"
          release_name: "${{ env.version }}${{ env.dev == 'true' && '-dev-' || '' }}${{ env.dev == 'true' && env.date || '' }}"
          draft: false
          prerelease: ${{ env.dev == 'true' }}
          generate_release_notes: false
